

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "المنشورات"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
      - { label: "المحتوى", name: "body", widget: "markdown" }
      - { label: "الصورة", name: "image", widget: "image", required: false }

  - name: "team"
    label: "أعضاء الهيكل الإداري"
    folder: "content/team"
    create: true
    slug: "{{name}}"
    fields:
      - { label: "الاسم", name: "name", widget: "string" }
      - { label: "المنصب", name: "role", widget: "string" }
      - { label: "التخصص", name: "major", widget: "string" }
      - { label: "الصورة", name: "avatar", widget: "image", required: false }
